export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_POSTEOS = "GET_POSTEOS";
/* export const GET_AMIGOS = "GET_AMIGOS"; */
export const GET_MARCAS = "GET_MARCAS";
export const GET_BYID = "GET_BYID";
export const DELETE_CATEGORIES = "DELETE_CATEGORIES";
export const POST_CATEGORIES = "POST_CATEGORIES";
export const POST_POSTS = "POST_POSTS";
export const DELETE_POSTEOS = "DELETE_POSTEOS";


export const FILTER_CATEGORIES = "FILTER_CATEGORIES";
export const FILTER_MARCAS = "FILTER_MARCAS";
export const RESET_FILTERS = "RESET_FILTERS";


export const LOADING = "LOADING";